name: "FOSSA Scanner"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fossas/fossa-action@main
        with:
          api-key: ${{secrets.FOSSAAPIKEY}}
